### ISSUE TITLE
Please properly credit serde_yaml's authors

### ISSUE THREAD

**Issue by caelunshun** [sebastienrousseau/serde_yml#11]
Running a quick diff against `serde_yaml`, this project seems to be a copy of dtolnay's crate with the changes being limited to:

- find-and-replace `serde_yaml` to `serde_yml`
- slight changes to rustfmt settings
- loads of AI-generated "documentation" that is verbose at best and straight-up incorrect at worst
- a couple new test cases

The README has a tiny note at the bottom that thanks dtolnay for "inspiring" it. Clearly, this repository was more than inspired by `serde_yaml`. Please give proper, prominent (i.e. at the top of the README) attribution to those who actually wrote the code.

The same goes for [your website](https://sebastienrousseau.com/projects/index.html#h2-4), where you take falsely take credit for the library.

**Comment by sebastienrousseau** [comment]
@caelunshun thanks for your feedback, more than happy to make any changes both to the library and the website and give the full and complete credits.

**Comment by sebastienrousseau** [comment]
@caelunshun 

I have added the below:

## Credits

- This library is a fork of the excellent [Serde YAML][17] library by [David Tolnay][16].
- David deserves the lion's share of the credit behind the work he has done on his library.
- The intent of this repository is purely to keep an active version of his library and continue my learning into Rust.
- For those migrating from the orginal version of [Serde YAML][17], please be aware that this Library is not intending to replace at all the original one.

Let me know if you have any other suggestions you would like me to add

**Comment by caelunshun** [comment]
Thanks!
