### ISSUE TITLE
Nested enums

### ISSUE THREAD

**Issue by asomers** [sebastienrousseau/serde_yml#13]
Thanks for continuing to maintain this important crate.  Do you plan to add new features, too?  If so, I'd like you to consider support for nested enums.  There were some good ideas over here.
https://github.com/dtolnay/serde-yaml/issues/363

**Comment by sebastienrousseau** [comment]
@asomers Thanks for your help and support. I will look into this.

**Comment by sebastienrousseau** [comment]
@asomers Changes merged to v0.0.7. Thanks!
