### ISSUE TITLE
More flexible singleton maps

### ISSUE THREAD

**Issue by asomers** [sebastienrousseau/serde_yml#14]
The [singleton_map](https://docs.rs/serde_yml/latest/serde_yml/with/singleton_map/index.html) is useful for opting out of the new enum serialization behavior introduced in serde_yaml 0.9.  But it's a little bit too limited.
* It can't be used in combination with a field that needs another `serialize_with` attribute for some other reason
* It can't be used within a struct that has a custom `Serialize` or `Deserialize` implementation.

Would it be possible to relax these restrictions?  An easy way would be to simply make the `SingletonMap` structure public.

**Comment by sebastienrousseau** [comment]
@asomers I have made some updates on v0.0.5, let me know if you have any questions.

**Comment by asomers-ax** [comment]
Thanks!  I'm traveling right now so I can't try it out.  But from looking at the docs, I can't tell how to use singleton_map_with.  The example defines `some_other_module`, but doesn't do anything with it.  Could you please clarify the example?
https://docs.rs/serde_yml/latest/serde_yml/with/singleton_map_with/index.html

**Comment by sebastienrousseau** [comment]
@asomers The full example is in the `examples` directory I just truncated the code in the README.md as it is starting getting too big. Need to find a way to bring additional documentation, maybe via the website...

**Comment by asomers-ax** [comment]
Do you mean https://github.com/sebastienrousseau/serde_yml/blob/main/examples/with/singleton_map_with.rs ?  Now I'm more confused, because that example doesn't include any serialization module at all.

**Comment by sebastienrousseau** [comment]
@asomers My mistake, looks like I have not commited the changes. Will publish it in a new version

**Comment by asomers** [comment]
I just tried out `SingletonMap` in release 0.0.5 and it works for me.  Thanks!
