### ISSUE TITLE
doc tests are not thread-safe

### ISSUE THREAD

**Issue by asomers** [sebastienrousseau/serde_yml#20]
Some of the doc tests create directories in PWD.  For example, the test for `macro_create_directories`.  Unless run with `--test-threads=1`, `cargo test` will frequently fail.  Instead, all doc tests that must create files or directories should use a tempdir.

**Comment by sebastienrousseau** [comment]
@asomers thanks. This will be part of https://github.com/sebastienrousseau/serde_yml/pull/24

**Comment by sebastienrousseau** [comment]
@asomers Changes merged to v0.0.7. Thanks!
