### ISSUE TITLE
Bogus copyright claims

### ISSUE THREAD

**Issue by asomers** [sebastienrousseau/serde_yml#22]
This crate is a fork of @dtolnay's serde-yaml.  But the source code includes copyright claims that assign all credit to "Serde YML, Seamless YAML Serialization for Rust".  For example, at the top of src/value/from.rs.  That's violation of dtolnay's license.  All of those claims should be removed except for within files that are wholly written by @sebastienrousseau (and not just moved from a different file).  Also, is "Serde YML, Seamless YAML Serialization for Rust" a legal entity?  If not, then it cannot own a copyright.

**Comment by asomers** [comment]
You'll just need inspect your code file-by-file.  For that matter, I don't even know if dtolnay is that original author of all of this, so it wouldn't be correct to simply credit him everywhere.  I suggest you just remove any copyright claims that you've added to preexisting code.

**Comment by sebastienrousseau** [comment]
@asomers Thanks for the help, I have removed all the claims on each files and just let the licenses MIT and Apache on the root. New release from PR `https://github.com/sebastienrousseau/serde_yml/pull/23` should be live quickly. Thanks again

**Comment by sebastienrousseau** [comment]
Close with release 0.0.6
