### ISSUE TITLE
Is it a fork of the serde-yaml?

### ISSUE THREAD

**Issue by SVilgelm** [sebastienrousseau/serde_yml#5]
Hi,

this looks like a fork of archived serde-yaml, but with some extra stuff. If it is true, could you please add a couple of words to readme?

It would be great to have a maintainable fork. But it looks like a bit unethical or even suspicious now

**Comment by sebastienrousseau** [comment]
Hi @SVilgelm 

You are correct, it is a fork of the archived `serde-yaml` and I am just starting doing changes and various updates. 

I believe I have added a special thanks to David Tolnay the author of `serde-yaml` at the bottom of the README. But more than happy to add any other words that you feel will explain better.

I agree on the maintainable fork, and I am convinced other maintainers will be able to resurrect the current `serde-yaml` crate and maintain it long term.

No intentions on my side to be unethical in any ways, I wanted to ensure I could still continue using `serde-yaml` in other libraries I am using without having deprecation warnings and without changing much code. 

It is also a good way for me to continue on my long journey to learn Rust.

**Comment by russellbanks** [comment]
Could you possibly add to the ReadMe what the different is between this and serde-yaml, even if it's just mentioning that it will be maintained? I imagine there will be lots of people (like me) who are looking for a maintained fork to serde-yaml and will come across this.

**Comment by sebastienrousseau** [comment]
@russellbanks Sure I will update the readme file.
