### ISSUE TITLE
Complexity of language used in documentation

### ISSUE THREAD

**Issue by russellbanks** [sebastienrousseau/serde_yml#9]
The language used in the documentation is quite verbose and complex and even if it's not, it reads as if it was AI-generated.

Take the first paragraph of the FAQ as an example:

> Welcome to the Serde YML FAQ section, your go-to resource for understanding and mastering YAML serialization and deserialization in Rust. Whether you're new to Serde YML or an experienced user, this comprehensive guide addresses common questions and provides practical examples to help you effectively utilize the library in your projects. Discover the benefits of Serde YML, learn how to configure and customize its behaviour, and explore its seamless integration with the Serde framework.

These sentences are essentially saying "Here's the FAQ which has some answers to common questions you might have". Instead, it doesn't achieve much and reads as if ChatGPT was asked to write a paragraph about an FAQ. As a reader, it feels like a salesperson is trying to sell me the library when I just want to find out what I need to add to my code to use it.

Please consider rewriting the documentation to be clearer, shorter, and easier to read. It's much more accessible if it's straight to the point.

**Comment by dtolnay** [comment]
Be aware that much of the crate contents are also AI-generated.

**Comment by sebastienrousseau** [comment]
@dtolnay and @russellbanks Thank you very much for your feedback. 

I will take your advice on simplifying the content and improve it to the best I can.

It is correct that the documentation has been generated with the help of AI tools available on my IDE. 

I guess I need to find the right balance.

**Comment by JadKHaddad** [comment]
sus

**Comment by bitdivine** [comment]
Would it make sense to start again?  I'm assuming good faith but perhaps letting your enthusiasm for AI break trust.  Maybe do a hard reset to the last @dtolnay commit, assign some reviewers with a solid track record and step forwards from there?

**Comment by bitdivine** [comment]
Would it make sense to start again.  Assuming good faith but perhaps letting your enthusiasm for AI break trust.  Maybe do a hard reset to the last @dtolnay commit, assign some reviewers and step forwards from there?  Or maybe a good home for this is https://github.com/orgs/serde-rs/repositories ?

**Comment by sebastienrousseau** [comment]
@russellbanks Website has been removed for now until I re-visit it with the correct content. Thanks for your help
